# Generated by Django 4.0.6 on 2022-07-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bpm', models.SmallIntegerField()),
                ('wrap', models.ImageField(default='wraps/S.svg', upload_to='wraps/')),
                ('wave', models.FileField(default='', upload_to='audio/wave/')),
                ('mp3', models.FileField(default='', upload_to='audio/mp3/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beats.artist')),
            ],
        ),
    ]
