# Generated by Django 4.0.6 on 2022-07-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='mp3',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='wave',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='wrap',
        ),
    ]
