# Generated by Django 4.0.6 on 2022-07-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_remove_beat_mp3_remove_beat_wave_remove_beat_wrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='created',
        ),
    ]
