# Generated by Django 4.0.6 on 2022-07-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_beat_mp3_beat_wave_beat_wrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='mp3',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='wave',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='wrap',
        ),
    ]
