# Generated by Django 4.0.6 on 2022-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_beat_mp3_beat_wave_beat_wrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beat',
            name='listenings',
            field=models.IntegerField(default=0),
        ),
    ]
